import { getCache, putCache, invalidateCache } from "./cache.js";
import { supabaseRest } from "./supabase.js";
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function clean(v){const s=String(v??"").trim();return s||null}
function key(v){return clean(v)?.toUpperCase().replace(/[^A-Z0-9]/g,"")||null}
function isoDate(v){const s=clean(v);if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(s||""))return null;const d=new Date(s+'T00:00:00Z');return d.toISOString().slice(0,10)===s?s:null}
function err(message,status=400,code="BAD_REQUEST"){const e=new Error(message);e.status=status;e.code=code;return e}
async function ownedCar(env,user,token,carId){const rows=await supabaseRest(env,`cars?select=id,registration_no&id=eq.${encodeURIComponent(carId)}&user_id=eq.${encodeURIComponent(user.id)}&limit=1`,{method:"GET"},token);return rows?.[0]||null}
function decorate(rows){const now=today();const valid=rows.filter(r=>r.expiry_date).sort((a,b)=>String(b.expiry_date).localeCompare(String(a.expiry_date)));const current=valid.find(r=>String(r.expiry_date)>=now)||null;return rows.map(r=>({...r,puc_status:current?.id===r.id?"current":"archive"})).sort((a,b)=>String(b.expiry_date||"").localeCompare(String(a.expiry_date||"")))}
export async function listPucHistory(env,user,userToken,carId=null){const keyName=carId?`puc:${user.id}:${carId}`:`puc:${user.id}`;const cached=await getCache(env,keyName);if(cached)return decorate(cached);const filters=[`user_id=eq.${encodeURIComponent(user.id)}`,"order=expiry_date.desc.nullslast,created_at.desc"];if(carId)filters.push(`car_id=eq.${encodeURIComponent(carId)}`);const data=await supabaseRest(env,`puc_history?select=*&${filters.join("&")}`,{method:"GET"},userToken);await putCache(env,keyName,user.id,"puc",data);return decorate(data)}
export async function createPuc(env,user,userToken,input){const carId=clean(input?.car_id),cert=clean(input?.certificate_number),test=isoDate(input?.test_date),valid=isoDate(input?.valid_until),cost=input?.cost==null?null:Number(input.cost);if(!carId||!cert||!test||!valid)throw err("PUC certificate number, test date and validity are required.");if(test>valid)throw err("PUC validity cannot be earlier than test date.");if(cost!=null&&!Number.isFinite(cost))throw err("PUC fees must be a valid number.");if(!(await ownedCar(env,user,userToken,carId)))throw err("Vehicle ownership verification failed.",403,"FORBIDDEN");const rows=await supabaseRest(env,`puc_history?select=*&car_id=eq.${encodeURIComponent(carId)}&user_id=eq.${encodeURIComponent(user.id)}`,{method:"GET"},userToken);const existing=rows.find(r=>key(r.certificate_number)===key(cert));if(existing){const patch={};if(!existing.issue_date&&test)patch.issue_date=test;if(!existing.expiry_date&&valid)patch.expiry_date=valid;if(existing.cost==null&&input?.cost!=null)patch.cost=input.cost;if(Object.keys(patch).length)await supabaseRest(env,`puc_history?id=eq.${encodeURIComponent(existing.id)}&car_id=eq.${encodeURIComponent(carId)}&user_id=eq.${encodeURIComponent(user.id)}`,{method:"PATCH",body:JSON.stringify(patch)},userToken);await invalidateCache(env,`puc:${user.id}:${carId}`);return{duplicate:true,already_saved:true,puc_id:existing.id}}const inserted=await supabaseRest(env,"puc_history",{method:"POST",body:JSON.stringify({user_id:user.id,car_id:carId,certificate_number:cert,issue_date:test,expiry_date:valid,cost:input?.cost??null,event_type:"snapshot",source:"browser-extraction"})},userToken);const row=Array.isArray(inserted)?inserted[0]:inserted;if(!row?.id)throw err("PUC could not be saved.",500,"SAVE_FAILED");await invalidateCache(env,`puc:${user.id}:${carId}`);return{duplicate:false,puc_id:row.id,puc_status:valid>=today()?"current":"archive"}}
